"""appointment reminders and merchant reminder offsets

Revision ID: 01d592a90b44
Revises: c9699cf6ce8d
Create Date: 2026-09-02 00:23:08.271276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d592a90b44'
down_revision: Union[str, Sequence[str], None] = 'c9699cf6ce8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_reminders',
    sa.Column('reminder_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('offset_hours', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('reminder_id'),
    sa.UniqueConstraint('appointment_id', 'offset_hours')
    )
    op.create_index(op.f('ix_appointment_reminders_appointment_id'), 'appointment_reminders', ['appointment_id'], unique=False)
    # server_default backfills existing merchant rows, then gets dropped so
    # new rows rely on the Python-side model default going forward -- same
    # two-step pattern as e3bd8e8e2e80's created_via/payment_status/timezone
    # columns (autogenerate emitted a bare NOT NULL with no default here,
    # which would fail against any merchant row that already exists).
    op.add_column('merchants', sa.Column('reminder_offsets_hours', sa.JSON(), nullable=False, server_default='[24]'))
    op.alter_column('merchants', 'reminder_offsets_hours', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'reminder_offsets_hours')
    op.drop_index(op.f('ix_appointment_reminders_appointment_id'), table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    # ### end Alembic commands ###
