"""add merchant kitchen details

Revision ID: 08c207f9f086
Revises: 31e66a073224
Create Date: 2026-08-06 11:22:38.523665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c207f9f086'
down_revision: Union[str, Sequence[str], None] = '31e66a073224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('kitchen_address_line1', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('kitchen_address_line2', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('kitchen_city', sa.String(length=120), nullable=True))
    op.add_column('merchants', sa.Column('kitchen_pincode', sa.String(length=16), nullable=True))
    op.add_column('merchants', sa.Column('cuisine_type', sa.String(length=120), nullable=True))
    op.add_column('merchants', sa.Column('fssai_license_no', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'fssai_license_no')
    op.drop_column('merchants', 'cuisine_type')
    op.drop_column('merchants', 'kitchen_pincode')
    op.drop_column('merchants', 'kitchen_city')
    op.drop_column('merchants', 'kitchen_address_line2')
    op.drop_column('merchants', 'kitchen_address_line1')
    # ### end Alembic commands ###
