"""add whatsapp flow id and private key to whatsapp_business_accounts

Revision ID: 0c07327c3f08
Revises: badd83266c3c
Create Date: 2026-08-16 23:28:08.871113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c07327c3f08'
down_revision: Union[str, Sequence[str], None] = 'badd83266c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_business_accounts', sa.Column('whatsapp_flow_id', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_business_accounts', sa.Column('flow_private_key_encrypted', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_business_accounts', 'flow_private_key_encrypted')
    op.drop_column('whatsapp_business_accounts', 'whatsapp_flow_id')
    # ### end Alembic commands ###
