"""add processed_whatsapp_messages

Revision ID: 31e66a073224
Revises: 60d2ca6b9bf0
Create Date: 2026-08-06 10:49:54.466410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e66a073224'
down_revision: Union[str, Sequence[str], None] = '60d2ca6b9bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_whatsapp_messages',
    sa.Column('processed_message_id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('processed_message_id')
    )
    op.create_index(op.f('ix_processed_whatsapp_messages_merchant_id'), 'processed_whatsapp_messages', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_processed_whatsapp_messages_whatsapp_message_id'), 'processed_whatsapp_messages', ['whatsapp_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_whatsapp_messages_whatsapp_message_id'), table_name='processed_whatsapp_messages')
    op.drop_index(op.f('ix_processed_whatsapp_messages_merchant_id'), table_name='processed_whatsapp_messages')
    op.drop_table('processed_whatsapp_messages')
    # ### end Alembic commands ###
