"""add appointment booking

Revision ID: 3e2e2914b3be
Revises: 50fa02971d49
Create Date: 2026-08-26 18:21:42.605271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2e2914b3be'
down_revision: Union[str, Sequence[str], None] = '50fa02971d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_appointment_counters',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('next_appointment_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_number', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('whatsapp_conversation_ref', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('appointment_id'),
    sa.UniqueConstraint('merchant_id', 'appointment_number')
    )
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_merchant_id'), 'appointments', ['merchant_id'], unique=False)
    # ### end Alembic commands ###

    # server_default=false() backfills every existing merchant row to
    # False, then gets dropped so new rows rely on the Python-side model
    # default (Merchant.appointment_booking_enabled) going forward --
    # same two-step pattern as c01e9485d53e's is_active column.
    op.add_column(
        'merchants',
        sa.Column(
            'appointment_booking_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.alter_column('merchants', 'appointment_booking_enabled', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'appointment_booking_enabled')
    op.drop_index(op.f('ix_appointments_merchant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('merchant_appointment_counters')
    # ### end Alembic commands ###
