"""add orders and whatsapp_business_accounts indexes

Revision ID: 41a1324a64a2
Revises: fcd1cd201c55
Create Date: 2026-09-07 13:22:44.785429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '41a1324a64a2'
down_revision: Union[str, Sequence[str], None] = 'fcd1cd201c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_merchant_fulfillment_status_placed_at', 'orders', ['merchant_id', 'fulfillment_status', 'placed_at'], unique=False)
    op.create_index('ix_whatsapp_business_accounts_phone_number_id_unique', 'whatsapp_business_accounts', ['phone_number_id'], unique=True, postgresql_where=sa.text('phone_number_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whatsapp_business_accounts_phone_number_id_unique', table_name='whatsapp_business_accounts', postgresql_where=sa.text('phone_number_id IS NOT NULL'))
    op.drop_index('ix_orders_merchant_fulfillment_status_placed_at', table_name='orders')
    # ### end Alembic commands ###
