"""add notification templates

Revision ID: 5a6563afe0db
Revises: 08c207f9f086
Create Date: 2026-08-06 11:46:46.652184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6563afe0db'
down_revision: Union[str, Sequence[str], None] = '08c207f9f086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('notification_kind', sa.String(length=32), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('merchant_id', 'notification_kind')
    )
    op.create_index(op.f('ix_notification_templates_merchant_id'), 'notification_templates', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_templates_merchant_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
