"""add whatsapp_business_accounts, merchant_payment_credentials, payment_events

Revision ID: 60d2ca6b9bf0
Revises: 631b405088f1
Create Date: 2026-08-06 10:24:54.402513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d2ca6b9bf0'
down_revision: Union[str, Sequence[str], None] = '631b405088f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_payment_credentials',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_key_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_key_secret_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('whatsapp_business_accounts',
    sa.Column('waba_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('meta_waba_id', sa.String(length=255), nullable=True),
    sa.Column('phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('access_token_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('token_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=32), nullable=False),
    sa.Column('webhook_subscribed', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('waba_id')
    )
    op.create_index(op.f('ix_whatsapp_business_accounts_merchant_id'), 'whatsapp_business_accounts', ['merchant_id'], unique=True)
    op.create_table('payment_events',
    sa.Column('payment_event_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('payment_event_id')
    )
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_provider_payment_id'), 'payment_events', ['provider_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_provider_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_whatsapp_business_accounts_merchant_id'), table_name='whatsapp_business_accounts')
    op.drop_table('whatsapp_business_accounts')
    op.drop_table('merchant_payment_credentials')
    # ### end Alembic commands ###
