"""add flow_image_base64 to menu_items

Revision ID: 6b4eed341b93
Revises: 0c07327c3f08
Create Date: 2026-08-17 01:44:26.125601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4eed341b93'
down_revision: Union[str, Sequence[str], None] = '0c07327c3f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('flow_image_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'flow_image_base64')
    # ### end Alembic commands ###
