"""Add billing plans, subscriptions, billing events

Revision ID: 80131b7ad897
Revises: a696b23f8aeb
Create Date: 2026-09-07 03:39:07.002868

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from billing.domain.seed_data import SEED_PLANS

# revision identifiers, used by Alembic.
revision: str = '80131b7ad897'
down_revision: Union[str, Sequence[str], None] = 'a696b23f8aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_billing_plans_table = sa.table(
    "billing_plans",
    sa.column("plan_id", sa.Uuid()),
    sa.column("tier", sa.String(length=16)),
    sa.column("billing_interval", sa.String(length=16)),
    sa.column("display_name", sa.String(length=64)),
    sa.column("price_inr", sa.Numeric(10, 2)),
    sa.column("order_cap", sa.Integer()),
    sa.column("whatsapp_flow_enabled", sa.Boolean()),
    sa.column("branding_required", sa.Boolean()),
    sa.column("razorpay_plan_id", sa.String(length=255)),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('billing_interval', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('price_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_cap', sa.Integer(), nullable=True),
    sa.Column('whatsapp_flow_enabled', sa.Boolean(), nullable=False),
    sa.Column('branding_required', sa.Boolean(), nullable=False),
    sa.Column('razorpay_plan_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('tier', 'billing_interval')
    )
    op.create_table('billing_events',
    sa.Column('billing_event_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('billing_event_id')
    )
    op.create_index(op.f('ix_billing_events_merchant_id'), 'billing_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_billing_events_provider_payment_id'), 'billing_events', ['provider_payment_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('past_due_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        _billing_plans_table,
        [{**plan, "plan_id": uuid.uuid4(), "razorpay_plan_id": None} for plan in SEED_PLANS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_billing_events_provider_payment_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_merchant_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
