"""add contact phone to customers and orders

Revision ID: a41fa29b8c86
Revises: 6b4eed341b93
Create Date: 2026-08-17 02:31:58.795857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41fa29b8c86'
down_revision: Union[str, Sequence[str], None] = '6b4eed341b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('default_contact_phone', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('contact_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'contact_phone')
    op.drop_column('customers', 'default_contact_phone')
    # ### end Alembic commands ###
