"""add merchants and staff_users

Revision ID: bccbc0736fb2
Revises: 
Create Date: 2026-08-06 08:40:10.681625

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bccbc0736fb2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_contact', sa.String(length=255), nullable=False),
    sa.Column('onboarding_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_owner_contact'), 'merchants', ['owner_contact'], unique=True)
    op.create_table('staff_users',
    sa.Column('staff_user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_or_phone', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('staff_user_id')
    )
    op.create_index(op.f('ix_staff_users_email_or_phone'), 'staff_users', ['email_or_phone'], unique=True)
    op.create_index(op.f('ix_staff_users_merchant_id'), 'staff_users', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_users_merchant_id'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_email_or_phone'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_merchants_owner_contact'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
