"""add revoked refresh tokens

Revision ID: c0ca5d2bcc50
Revises: 41a1324a64a2
Create Date: 2026-09-07 13:43:16.047588

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c0ca5d2bcc50'
down_revision: str | Sequence[str] | None = '41a1324a64a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_refresh_tokens',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('staff_user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.staff_user_id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revoked_refresh_tokens_expires_at'), 'revoked_refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_refresh_tokens_merchant_id'), 'revoked_refresh_tokens', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_revoked_refresh_tokens_staff_user_id'), 'revoked_refresh_tokens', ['staff_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_refresh_tokens_staff_user_id'), table_name='revoked_refresh_tokens')
    op.drop_index(op.f('ix_revoked_refresh_tokens_merchant_id'), table_name='revoked_refresh_tokens')
    op.drop_index(op.f('ix_revoked_refresh_tokens_expires_at'), table_name='revoked_refresh_tokens')
    op.drop_table('revoked_refresh_tokens')
    # ### end Alembic commands ###
