"""appointment payment link placeholder

Revision ID: c9699cf6ce8d
Revises: e3bd8e8e2e80
Create Date: 2026-09-02 00:20:25.727318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9699cf6ce8d'
down_revision: Union[str, Sequence[str], None] = 'e3bd8e8e2e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_events', sa.Column('appointment_id', sa.Uuid(), nullable=True))
    op.alter_column('payment_events', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payment_events_appointment_id'), 'payment_events', ['appointment_id'], unique=False)
    op.create_foreign_key(
        'fk_payment_events_appointment_id_appointments',
        'payment_events', 'appointments', ['appointment_id'], ['appointment_id'],
    )
    op.create_check_constraint('ck_payment_events_exactly_one_entity', 'payment_events', '(order_id IS NOT NULL) != (appointment_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_payment_events_exactly_one_entity', 'payment_events', type_='check')
    op.drop_constraint(
        'fk_payment_events_appointment_id_appointments', 'payment_events', type_='foreignkey'
    )
    op.drop_index(op.f('ix_payment_events_appointment_id'), table_name='payment_events')
    op.alter_column('payment_events', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payment_events', 'appointment_id')
    # ### end Alembic commands ###
