"""add whatsapp appointment flow id

Revision ID: f2bfa36941b5
Revises: c69624bf2d8b
Create Date: 2026-08-27 07:10:59.473915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bfa36941b5'
down_revision: Union[str, Sequence[str], None] = 'c69624bf2d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_business_accounts', sa.Column('whatsapp_appointment_flow_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_business_accounts', 'whatsapp_appointment_flow_id')
    # ### end Alembic commands ###
