"""unique partial index on payment_events provider_payment_id

Revision ID: fcd1cd201c55
Revises: 80131b7ad897
Create Date: 2026-09-07 13:06:50.927919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd1cd201c55'
down_revision: Union[str, Sequence[str], None] = '80131b7ad897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_provider_payment_id'), table_name='payment_events')
    op.create_index('ix_payment_events_provider_payment_id_unique', 'payment_events', ['provider_payment_id'], unique=True, postgresql_where=sa.text("provider_payment_id IS NOT NULL AND event_type IN ('payment_succeeded', 'payment_failed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_events_provider_payment_id_unique', table_name='payment_events', postgresql_where=sa.text("provider_payment_id IS NOT NULL AND event_type IN ('payment_succeeded', 'payment_failed')"))
    op.create_index(op.f('ix_payment_events_provider_payment_id'), 'payment_events', ['provider_payment_id'], unique=False)
    # ### end Alembic commands ###
